sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QaB/RKiB5AR5DjWLXzvvUpNUyhAxepjJcM0y1j6OA/sbUZ/Xc8veMKgBHfHPPVI+H5hT9on4gToZR5W+K3Zz7gMdx+oYpTqBAyFt41dKXHfdFSyr858CDQDHQXG65IeeMULsfdPITltXM0Sb94yAmzDwlXhOfoL+VbdcemxKBUF62fLxaE8xhYO0BC/ssKncyA6zMCbwo4WpK6vD2qoKaisXvyP7VhFSd4SR6XthCwS9m3NeswjTazI5eOqgXQJiBwG2JzG30EaoLPqPaGJTbhVAV1GG5AZ8rKIpDr3Kt2a0ihyp2x7ky+c4MDBpSTFBhnLiGu90XJXcA4kcfMzFTtERqua3iuNxQ2cKqfH1kvAI78fwNVBnPIzwWEy/Km6LtvOHIts7B/YEjS9QMuERHMhkIh2vvY/etWxXfLGO6c71a6hVOALaaLp1F8yUjRTZt1BzAOM0twgU/z8w+RPMCm6iWIo5xbuRD1865HXBIgLd4FzyxNrOWCHuiJcY0m0SeZMXEZcsAzqhJ6wG08zvsLJ2t278c0grrtlc+Ae29JBuMeYVFWI0gl1wzv17M5oPP3By/S48LFVwABZmHY8g2nlvVLl/IzzFGQ26VZ1AXFaCqriu3hr2UDEVDekfUk+30qSyBIu/q4sm1Kh5gYpjOOGSdwTfa18IReGKP3JM/AU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Tempting-of-Tavernake_5091
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy